### ISSUE TITLE
Set maui-linux as default branch

### ISSUE THREAD

**Issue by thomiel** [jsuarezruiz/maui-linux#36]
### Description

You declared maui-linux as the branch you accept pull request for. This should be the default branch as in the GitHub Repository settings then.

### Steps to Reproduce

just go to https://github.com/jsuarezruiz

### Version with bug

Unknown/Other (please specify)

### Last version that worked well

Unknown/Other

### Affected platforms

I was *not* able test on other platforms

### Affected platform versions

n/a

**Comment by jsuarezruiz** [comment]
Good suggestion, changed.

**Comment by knocte** [comment]
And what's the reason for using a different branch than master? Is it to make merges with upstream MAUI easier?
