### ISSUE TITLE
[Enhancement] Possible? Using gir.core for Gtk4

### ISSUE THREAD

**Issue by seriouz** [jsuarezruiz/maui-linux#8]
Did you guys notice [gir.core](https://github.com/gircore/gir.core)? Its a C# wrapper for different GObject based libraries like Gtk(4). It could be useful.
If not, close this issue ;)

**Comment by jsuarezruiz** [comment]
@seriouz Could you share more info about the current status, roadmap etc?

**Comment by seriouz** [comment]
@badcel Can you provide more informations?

**Comment by badcel** [comment]
We made some good progress and started generating properties and methods as we just merged our fundamental generator rewrite. We need to improve code quality, refactor a lot, get more API code coverage, get delegate generation working and probably more. Meaning it is still a lot of work and a long way to go but we are quite motivated.

We recently created our own [gir.core matrix chat channel](https://matrix.to/#/#gircore:matrix.org?via=matrix.org) where everyone who wants to take part in development or has a question or just wants to hang out can get easily in contact with us.

We hope to get some initial pre release nuget ready if we have better record / struct support but we don't have an ETA yet. This would hopefully lead to gather some early adopters and get valuable feedback. Any support in this phase to raise awareness of the library would be very appreciated.

Our initial statement can be found [here](https://github.com/jsuarezruiz/forms-gtk-progress/issues/31#issuecomment-801008024).

The [website](https://gircore.github.io/) contains some links and pictures.

**Comment by seriouz** [comment]
@badcel Thanks for the detailed answer! Is gir.core in a state where it could be used here in maui-linux, or should the current path of using GtkSharp with Gtk3 be further followed?

**Comment by badcel** [comment]
@seriouz I think I can't answer this as I don't know the ETA for some Gtk3/4 support plans for MAUI.

**Comment by jsuarezruiz** [comment]
We are progressing little by little, and we will have more and more implementations that would change if Gtk4 is used instead of Gtk3, so it would be interesting to make the change as soon as possible. 

It can always be done later, even after completing using Gtk 3, but it will require more effort. Anyway, this would require to validate Gtk 4 library status, license, etc.

**Comment by badcel** [comment]
If it should be a stable feature of dotnet 6 I think it is to early to adopt gir.core.

But it shouldn't be very hard to port over at a later point I'm time.
