### ISSUE TITLE
Update main-linux to recent version of dotnet/maui main

### ISSUE THREAD

**Issue by lytico** [jsuarezruiz/maui-linux#9]
### Description

@jsuarezruiz  Please update 

https://github.com/jsuarezruiz/maui-linux/tree/main-linux

to a recent version of https://github.com/dotnet/maui

### Reason

after that, i can merge & adopt

https://github.com/jsuarezruiz/maui-linux/tree/init-linux

add more additions

and make a recent pull request

**Comment by lytico** [comment]
@jsuarezruiz  just give me a not, if you don't have time, i'll make that and PR to https://github.com/jsuarezruiz/maui-linux/tree/main-linux

**Comment by jsuarezruiz** [comment]
The `main-linux` branch is now up to date. Will do this periodically every week.

**Comment by lytico** [comment]
https://github.com/jsuarezruiz/maui-linux/issues/2#issuecomment-823502047

> And then, merge this init-linux branch to main-linux.

how is the workflow then?

i merge init-linux branch to main-linux, adopt the changes, make a PR on main-linux.

then, every week: you **set** main-linux to dotnet/maui/main

so, what is the actual merged linux brach then?
