### ISSUE TITLE
Nuget packages: prerelease for each commit and non-prerelease for each git tag? via GitHub Actions

### ISSUE THREAD

**Issue by knocte** [jsuarezruiz/maui-linux#94]
### Description

Following up wrt this: https://github.com/jsuarezruiz/maui-linux/issues/90#issuecomment-2293274560

### Public API Changes

- Each commit in the `main` branch would map to a prerelease in nuget.org.
- Each git tag would map to a non-prerelease in nuget.org.

### Intended Use-Case

Easier to consume. (We currently consume this repo via git submodule but would prefer using nuget instead.)
We're open to create a PR for this, that can publish the packages in nuget.org with GitHubActions.

**Comment by knocte** [comment]
@jsuarezruiz ping? as you suggested in issue 90, I created an issue.

**Comment by jsuarezruiz** [comment]
> @jsuarezruiz ping? as you suggested in issue 90, I created an issue.

Sorry for the delay. Sounds good to me, go ahead with the PR for the GitHub Action etc if you want.
